---
title: "01_load"
author: "group22"
format:
  html:
    embed-resources: true
editor: visual
---

```{r}
df <- read.csv("diabetes_binary_5050split_health_indicators_BRFSS2015.csv")
head(df)
```

```{r}
str(df)
```

```{r}
summary(df)
```

```{r}
any(is.na(df))
```

```{r}
# Check if there are any duplicates in the data frame
if (any(duplicated(df))) {
  print("There are duplicates in the data frame.")
} else {
  print("No duplicates found in the data frame.")
}
```

```{r}
# Identify duplicated rows
duplicated_rows <- duplicated(df)

# Print the data frame with duplicated rows highlighted
print(cbind(df, is_duplicate = duplicated_rows))

# Remove duplicated rows
df <- df[!duplicated_rows, ]

# Print the data frame without duplicates
print(df)
```

```{r}
# Check if there are any duplicates in the data frame
if (any(duplicated(df))) {
  print("There are duplicates in the data frame.")
} else {
  print("No duplicates found in the data frame.")
}
```

```{r}
# Convert numerical variables to binary (1 if not zero, 0 otherwise)
df$HighBP <- ifelse(df$HighBP != 0, "YES", "NO")
df$HighChol <- ifelse(df$HighChol != 0, "YES", "NO")
str(df)
```

```{r}
summary(df)
```

```{r}
# Assuming your data frame is named 'my_data'
variable_types <- sapply(df, class)
print(variable_types)
```
